config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root 'groups#index'
  resources :groups, except: [:index, :show, :delete] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_many :groups_users
  has_many :users, through: :groups_users
  has_many :messages
  has_many :message_recipients

  def latest_message
    if self.messages.last == nil
      "まだメッセージはありません"
    elsif self.messages.last.image.url == nil
      self.messages.last.try(:body)
    else
      "画像が送信されました"
    end
  end
end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :message_recipients
  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :message_recipients

  scope :read_message, ->(group, user) { joins(:message_recipients).merge(MessageRecipient.where(group_id: group, user_id: user).read) }
  scope :unread_message, ->(group, user) { joins(:message_recipients).merge(MessageRecipient.where(group_id: group, user_id: user).unread) }
end

app/models/message_recipient.rb
class MessageRecipient < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :message

  enum read_flg: %w(unread read)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups_users
  has_many :groups, through: :groups_users
  has_many :messages
  has_many :message_recipients
  validates :name, presence: true

  scope :not_current_users, ->(group, user) { joins(:groups_users).merge(GroupsUser.where(["group_id = ? and user_id != ?", group, user])) }

  def join_group?(group)
    groups.include?(group)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def reject_user_not_belongs_to_group
    redirect_to :root unless current_user.join_group?(@group)
  end

  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  after_action :set_users_except_current_user, only: [:new, :edit]

  def index
    @groups = current_user.groups.includes(:messages)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループ作成成功"
    else
      flash.now[:alert] = "グループ作成失敗"
      render "new"
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    group = Group.find(params[:id])
    group.update(group_params)
    redirect_to root_path
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_users_except_current_user
    @users_except_current_user = User.not_current_users(@group, current_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_groups, :set_messages, only: [:index, :create]

  before_action :reject_user_not_belongs_to_group, only: :index

  def index
    @message = Message.new
    @users = User.where.not(id: current_user)
    @message.message_recipients.build
    group_message = MessageRecipient.where(group_id: @group, user_id: current_user)
    @read_messages = Message.read_message(@group, current_user)
    @unread_messages = Message.unread_message(@group, current_user)
    group_message.update_all(read_flg: "read")
  end

  def create
    @message = current_user.messages.new(message_params)
    group_message = MessageRecipient.where(group_id: @group, user_id: current_user)
    @read_messages = group_message.read
    @unread_messages = group_message.unread
    group_message.update_all(read_flg: "read")
    @unread_count_messages = unread_message_count(@group, @group.users.where.not(id: current_user))
    if @message.save
    flash[:notice] = "メッセージ送信成功"
      respond_to do |format|
        format.html
        format.json
      end
    else
      flash.now[:alert] = "メッセージ送信失敗"
      respond_to do |format|
        format.html
        format.json { render 'alert', handlers: 'jbuilder' }
      end
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image, message_recipients_attributes: [:group_id, :user_id, :message_id, :read_flg]).merge(group_id: params[:group_id])
  end

  def set_groups
    @groups = current_user.groups.includes(:messages)
    @group = Group.find(params[:group_id])
  end

  def set_messages
    @messages = @group.messages.includes(:user)
  end

  def unread_message_count(group,users)
    unread_message_count_hash = {}
    users.each do |user|
      unread_message_count_hash["#{user.id}"] = group.message_recipients.where(user_id: user.id).unread.size
    end
    return unread_message_count_hash
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    @users = User.where("id != #{current_user.id} and name LIKE(?)",  "#{params[:keyword]}%")
      respond_to do |format|
        format.json
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def form_title
    current_page?(new_group_path) ? "新規チャットグループ作成" : "チャットグループ編集"
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def message_date(message)
    message.created_at.to_s(:datetime)
  end

  def reading_judgment(group)
    group.message_recipients.where(user_id: current_user.id).unread.empty?
  end

  def read_message_count(message)
    message.message_recipients.read.size - 1
  end

  def read_message_member(message)
    read_members = User.joins(:message_recipients).merge(MessageRecipient.where(message_id: message.id).where.not(user_id: current_user.id).read)
    members = ""
    read_members.each do |read_member|
      members << "#{read_member.name}, "
    end
    return members
  end

  def unread_message_count(group)
    group.message_recipients.where(user_id: current_user.id).unread.size
  end
end

app/views/common/_flashmessage.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: key)

app/views/common/_leftbox.html.haml
.left-box
  .left-box__user-name
    = current_user.name
    = link_to edit_user_registration_path do
      %i.fa.fa-cog.left-box__user-name--setting
    = link_to new_group_path do
      %i.fa.fa-pencil-square-o.left-box__user-name--edit
  .left-box__talk
    - @groups.each do |group|
      = link_to group_messages_path(group) do
        .left-box__talk__detail{id: "left-box__talk"}
          .left-box__talk__detail--group{id: "left-box__talk-#{group.id}-user#{current_user.id}"}
            = group.name
          - unless reading_judgment(group)
            .left-box__talk__detail--unread_count
              %p
                = unread_message_count(group)
          .left-box__talk__detail--message{id: "left-box__talk__detail-#{group.id}"}
            = group.latest_message
  .left-box__footer

app/views/groups/_form.html.haml
.chat-group-form
  %h1
    = form_title
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバーを追加", class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input{placeholder: "追加したいユーザー名を入力してください", type: "text", id: 'chat-group-form__input'}
        #user-search-result
          %ul{id: 'list'}

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label チャットメンバー
      .chat-group-form__field--right
        %ul#chat-group-users
          %li.chat-group-user.clearfix
            .chat-group-user__name
              = current_user.name
              = hidden_field_tag('group[user_ids][]', current_user.id)
          = render partial: "groups/user", collection: @users_except_current_user

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", name: "commit", type: "submit", class: "chat-group-form__action-btn"



app/views/groups/_user.html.haml
%li.chat-group-user.clearfix
  .chat-group-user__name
    = user.name
    = hidden_field_tag('group[user_ids][]', user.id)
  .chat-group-user__btn.chat-group-user__btn--remove
    削除

app/views/groups/edit.html.haml
= render partial: "groups/form"

app/views/groups/index.html.haml
= render partial: "common/leftbox"

app/views/groups/new.html.haml
= render partial: "groups/form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv":"Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render partial: "common/flashmessage"
    = yield

app/views/messages/_message.html.haml
.right-box__message__box__detail--name
  = message.user.name
.right-box__message__box__detail--date
  = message_date(message)
- if message.body
  .right-box__message__box__detail--content
    = message.body
- if message.image.url
  .right-box__message__box__detail--image
    = image_tag message.image
- if message.user_id == current_user.id
  .right-box__message__box__detail--reading{title: "#{read_message_member(message)}"}
    = read_message_count(message)
    = " people have already read."

app/views/messages/index.html.haml
.wrapper
  .box
    = render partial: "common/leftbox"
    .right-box
      .right-box__group
        .right-box__group--name
          = @group.name
        .right-box__group--edit
          =link_to "Edit", edit_group_path(@group)
        .right-box__group--member
          Members:
          - @group.users.each do |user|
            = "#{user.name},"
      .right-box__message
        .right-box__message__box{id: 'right-box__message__box'}
          - @read_messages.each do |read_message|
            - if read_message.user_id == current_user.id
              .right-box__message__box__detail-current_user{data:{id: read_message.id}}
                = render 'message', message: read_message
            - else
              .right-box__message__box__detail-other_user{data:{id: read_message.id}}
                = render 'message', message: read_message
          - unless @unread_messages.empty?
            .right-box__message__unread{id: 'right-box__message__unread'}
              = "ここからが未読のメッセージです"
          - @unread_messages.each do |unread_message|
            .right-box__message__box__detail-other_user{data:{id: unread_message.id}}
              = render 'message', message: unread_message

      .right-box__send
        = form_for [@group, @message], html: {id: 'new_message'} do |f|
          = f.text_field :body, placeholder: "type a message", class: "right-box__send__input"
          = f.fields_for :message_recipients do |message|
            = message.hidden_field :group_id, value: "#{@group.id}"
            = message.hidden_field :user_id, value: "#{current_user.id}"
            = message.hidden_field :message_id, value: "#{@message.id}"
            = message.hidden_field :read_flg, value: :read
          - @users.each do |user|
            = f.fields_for :message_recipients do |message|
              = message.hidden_field :group_id, value: "#{@group.id}"
              = message.hidden_field :user_id, value: "#{user.id}"
              = message.hidden_field :message_id, value: "#{@message.id}"
              = message.hidden_field :read_flg, value: :unread
          %label.right-box__send--image
            = f.file_field :image
            %i.fa.fa-image
          = f.submit "Send", class: "right-box__send__button"